# Generated by Django 5.2.3 on 2025-06-11 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_specialization_specialistprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название палаты')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Палата',
                'verbose_name_plural': 'Палаты',
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20, verbose_name='Номер койки')),
                ('status', models.CharField(choices=[('FREE', 'Свободна'), ('OCCUPIED', 'Занята'), ('CLEANING', 'На санобработке'), ('REPAIR', 'На ремонте')], default='FREE', max_length=10, verbose_name='Статус')),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed', to='core.patient', verbose_name='Пациент')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='inpatient.ward', verbose_name='Палата')),
            ],
            options={
                'verbose_name': 'Койка',
                'verbose_name_plural': 'Койки',
                'ordering': ['ward', 'bed_number'],
                'unique_together': {('ward', 'bed_number')},
            },
        ),
    ]
