# Generated by Django 5.2.3 on 2025-06-12 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_specialization_specialistprofile'),
        ('inpatient', '0002_hospitalization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания к заявке')),
                ('status', models.CharField(choices=[('WAITING', 'Ожидает госпитализации'), ('FULFILLED', 'Госпитализирован'), ('CANCELLED', 'Отменена')], default='WAITING', max_length=10, verbose_name='Статус заявки')),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заявки')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requests', to='core.patient', verbose_name='Пациент')),
                ('requested_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inpatient.ward', verbose_name='Желаемая палата')),
            ],
            options={
                'verbose_name': 'Заявка на госпитализацию',
                'verbose_name_plural': 'Очередь на госпитализацию',
                'ordering': ['date_requested'],
            },
        ),
    ]
