# Generated by Django 5.2.3 on 2025-06-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_admissionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrequest',
            name='planned_admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата госпитализации'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='planned_discharge_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата выписки'),
        ),
    ]
