# Generated by Django 5.2.3 on 2025-06-12 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0004_admissionrequest_planned_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrequest',
            name='bed',
            field=models.ForeignKey(blank=True, help_text='Выберите конкретную койку для бронирования. Отобразится на диаграмме Ганта.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inpatient.bed', verbose_name='Забронированная койка'),
        ),
    ]
