# Generated by Django 5.2.3 on 2025-06-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('inpatient', '0005_admissionrequest_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrequest',
            name='source_commission_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admission_request', to='commissions.selectioncommitteeapplication', verbose_name='Исходное обращение в комиссию'),
        ),
    ]
