# Generated by Django 5.2.3 on 2025-06-11 18:08

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание документа')),
                ('document', models.FileField(upload_to=core.models.patient_directory_path, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Документ пациента',
                'verbose_name_plural': 'Документы пациентов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
