# Generated by Django 5.2.3 on 2025-06-12 18:05

from django.db import migrations


def create_default_ward(apps, schema_editor):
    Ward = apps.get_model('core', 'Ward')
    # Create a default ward if none exists
    if not Ward.objects.exists():
        Ward.objects.create(
            name='Общая палата',
            department='Общее отделение',
            floor=1,
            capacity=10,
            description='Общая палата по умолчанию',
            is_active=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ward_bed_patientadmission'),
    ]

    operations = [
        migrations.RunPython(create_default_ward, reverse_code=migrations.RunPython.noop),
    ]
