# Generated by Django 5.2.3 on 2025-06-12 18:07

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_default_ward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdocument',
            options={'ordering': ['-uploaded_at'], 'permissions': [('view_private_document', 'Может просматривать конфиденциальные документы')], 'verbose_name': 'Документ пациента', 'verbose_name_plural': 'Документы пациентов'},
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='admission_type',
            field=models.CharField(choices=[('planned', 'Плановая'), ('emergency', 'Экстренная'), ('transfer', 'Перевод из другого учреждения')], default='planned', max_length=20, verbose_name='Тип госпитализации'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='attending_physician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_admissions', to=settings.AUTH_USER_MODEL, verbose_name='Лечащий врач'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admissions', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер полиса'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страховая компания'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная госпитализация'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='payment_type',
            field=models.CharField(choices=[('oms', 'ОМС'), ('dms', 'ДМС'), ('paid', 'Платно'), ('other', 'Иное')], default='oms', max_length=10, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='referral_diagnosis',
            field=models.TextField(blank=True, verbose_name='Диагноз при направлении'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер комнаты'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='treatment_plan',
            field=models.TextField(blank=True, verbose_name='План лечения'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.ward', verbose_name='Палата'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='document_type',
            field=models.CharField(choices=[('referral', 'Направление'), ('medical_report', 'Медицинское заключение'), ('test_results', 'Результаты анализов'), ('prescription', 'Рецепт'), ('insurance', 'Страховой полис'), ('id_document', 'Удостоверение личности'), ('consent', 'Согласие на лечение'), ('discharge_summary', 'Выписка из истории болезни'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Если отмечено, документ будет виден только администраторам и лечащим врачам', verbose_name='Конфиденциальный документ'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загружено пользователем'),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='admission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время поступления'),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_admission', to='core.bed', verbose_name='Койка'),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='Клинический диагноз'),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выписки'),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to=settings.AUTH_USER_MODEL, verbose_name='Врач, оформивший госпитализацию'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание документа'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='document',
            field=models.FileField(help_text='Поддерживаемые форматы: PDF, DOC, DOCX, JPG, PNG (макс. 10 МБ)', upload_to=core.models.patient_directory_path, verbose_name='Файл'),
        ),
    ]
