# Generated by Django 5.2.3 on 2025-06-14 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_1c_url', models.URLField(blank=True, verbose_name='1С: URL сервиса')),
                ('service_1c_key', models.CharField(blank=True, max_length=128, verbose_name='1С: API-ключ')),
                ('sms_provider', models.CharField(blank=True, max_length=64, verbose_name='SMS-провайдер')),
                ('sms_api_key', models.CharField(blank=True, max_length=128, verbose_name='SMS API-ключ')),
                ('email_host', models.CharField(blank=True, max_length=128, verbose_name='SMTP сервер')),
                ('email_user', models.CharField(blank=True, max_length=128, verbose_name='SMTP пользователь')),
                ('email_password', models.CharField(blank=True, max_length=128, verbose_name='SMTP пароль')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
            ],
            options={
                'verbose_name': 'Интеграции и API',
                'verbose_name_plural': 'Интеграции и API',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('clinic_name', models.CharField(default='Реабилитационный центр', max_length=255, verbose_name='Название клиники')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Часовой пояс')),
                ('date_format', models.CharField(default='DD.MM.YYYY', max_length=32, verbose_name='Формат даты')),
                ('language', models.CharField(default='ru', max_length=8, verbose_name='Язык')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Техническое обслуживание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Логотип')),
                ('color_theme', models.CharField(default='default', max_length=32, verbose_name='Цветовая схема')),
            ],
            options={
                'verbose_name': 'Системные настройки',
                'verbose_name_plural': 'Системные настройки',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-timestamp'],
            },
        ),
    ]
