# Generated by Django 5.2.3 on 2025-06-13 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved at'),
        ),
        migrations.AddField(
            model_name='document',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
    ]
