# Generated by Django 5.2.3 on 2025-06-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_approved_at_document_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'permissions': [('approve_document', 'Can approve document')], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
