# Generated by Django 5.2.3 on 2025-06-11 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_patientdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabilitationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('INPATIENT', 'Стационарная'), ('OUTPATIENT', 'Амбулаторная'), ('HOME_BASED', 'На дому')], max_length=20, verbose_name='Форма реабилитации')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланирована'), ('ACTIVE', 'Активна'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='PLANNED', max_length=20, verbose_name='Статус')),
                ('goal', models.TextField(verbose_name='Цель реабилитации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehabilitation_programs', to='core.patient', verbose_name='Пациент')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ведущий специалист')),
            ],
            options={
                'verbose_name': 'Программа реабилитации',
                'verbose_name_plural': 'Программы реабилитации',
                'ordering': ['-start_date'],
            },
        ),
    ]
