# Generated by Django 5.2.3 on 2025-06-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab_programs', '0002_rehabactivity_scheduledactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledactivity',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='scheduledactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rehab_programs.rehabactivity', verbose_name='Процедура'),
        ),
        migrations.AlterField(
            model_name='scheduledactivity',
            name='scheduled_date',
            field=models.DateTimeField(verbose_name='Запланированная дата и время проведения'),
        ),
    ]
