# Generated by Django 5.2.3 on 2025-06-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab_programs', '0003_scheduledactivity_specialist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehabactivity',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Тип реабилитационной процедуры', 'verbose_name_plural': 'Справочник типов процедур'},
        ),
        migrations.AddField(
            model_name='rehabactivity',
            name='category',
            field=models.CharField(choices=[('PHYSIO', 'Физиотерапия'), ('PSYCHO', 'Психологическая поддержка'), ('DIAGNOSTIC', 'Диагностика'), ('SPEECH', 'Логопедия'), ('MASSAGE', 'Массаж'), ('OTHER', 'Прочее')], default='OTHER', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='rehabactivity',
            name='default_duration',
            field=models.PositiveIntegerField(default=30, help_text='Длительность процедуры в минутах', verbose_name='Длительность (мин)'),
        ),
        migrations.AddField(
            model_name='rehabactivity',
            name='required_equipment',
            field=models.TextField(blank=True, verbose_name='Необходимое оборудование'),
        ),
    ]
