# Generated by Django 5.2.3 on 2025-06-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код МКБ-10')),
                ('name', models.TextField(verbose_name='Название болезни')),
            ],
            options={
                'verbose_name': 'Болезнь (МКБ-10)',
                'verbose_name_plural': 'Справочник МКБ-10',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField(verbose_name='Дата постановки диагноза')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medical_history.icd10disease', verbose_name='Диагноз по МКБ-10')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='core.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские записи',
                'ordering': ['-diagnosis_date'],
            },
        ),
    ]
