# Generated by Django 5.2.3 on 2025-06-11 18:16

from django.db import migrations

ICD10_DATA = [
    ('F84.0', 'Детский аутизм'),
    ('G80.0', 'Спастический церебральный паралич'),
    ('F90.0', 'Нарушение активности и внимания'),
    ('R62.0', 'Задержка этапов развития'),
    ('I69.4', 'Последствия инсульта, не уточненные как кровоизлияние или инфаркт мозга'),
    ('Z73.6', 'Ограничения деятельности, вызванные снижением трудоспособности'),
]

def forwards_func(apps, schema_editor):
    ICD10Disease = apps.get_model('medical_history', 'ICD10Disease')
    for code, name in ICD10_DATA:
        ICD10Disease.objects.create(code=code, name=name)

def reverse_func(apps, schema_editor):
    ICD10Disease = apps.get_model('medical_history', 'ICD10Disease')
    codes = [item[0] for item in ICD10_DATA]
    ICD10Disease.objects.filter(code__in=codes).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=reverse_func),
    ]
