# Generated by Django 5.2.3 on 2025-06-12 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionCommitteeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО пациента')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('address', models.TextField(blank=True, verbose_name='Адрес регистрации')),
                ('diagnosis', models.TextField(help_text='Со слов пациента или из направления', verbose_name='Предварительный диагноз')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обращения')),
                ('operator_comment', models.TextField(blank=True, verbose_name='Комментарий оператора')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время записи в отб. комиссию')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('SCHEDULED', 'Запланирована встреча'), ('COMPLETED', 'Встреча состоялась'), ('APPROVED', 'Одобрено для врачебной комиссии'), ('REJECTED', 'Отклонено'), ('CLARIFY', 'Требует уточнения')], default='NEW', max_length=10, verbose_name='Статус заявки')),
                ('committee_comment', models.TextField(blank=True, verbose_name='Комментарий отборочной комиссии')),
                ('operator', models.ForeignKey(help_text='Сотрудник, принявший обращение', on_delete=django.db.models.deletion.PROTECT, related_name='created_applications', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Заявка в отборочную комиссию',
                'verbose_name_plural': 'Заявки в отборочную комиссию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCommitteeConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время записи во врачебную комиссию')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает записи'), ('SCHEDULED', 'Запланирована встреча'), ('CONCLUDED', 'Решение принято')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('final_decision', models.CharField(blank=True, choices=[('HOSPITAL', 'Рекомендована госпитализация'), ('OUTPATIENT', 'Рекомендовано амбулаторное лечение'), ('HOME_CARE', 'Рекомендовано лечение на дому'), ('REJECTED', 'Отклонено')], max_length=10, verbose_name='Итоговое решение')),
                ('committee_comment', models.TextField(blank=True, verbose_name='Комментарий врачебной комиссии')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_conclusion', to='commissions.selectioncommitteeapplication', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Заключение врачебной комиссии',
                'verbose_name_plural': 'Заключения врачебной комиссии',
                'ordering': ['-application__created_at'],
            },
        ),
    ]
