# Generated by Django 5.2.3 on 2025-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_selectioncommitteeapplication_appointment_date'),
        ('medical_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectioncommitteeapplication',
            name='icd10_codes',
            field=models.ManyToManyField(blank=True, help_text='Выберите соответствующие коды МКБ-10', related_name='selection_applications', to='medical_codes.icd10code', verbose_name='Коды МКБ-10'),
        ),
    ]
