# Generated by Django 5.2.3 on 2025-06-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('is_category', models.BooleanField(default=False, verbose_name='Это категория?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='medical_codes.icd10code', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Код МКБ-10',
                'verbose_name_plural': 'Коды МКБ-10',
                'ordering': ['code'],
            },
        ),
    ]
